direction: right
near: bottom-center
local: "Локальный запуск" {
  shape: image
  icon: pc-icon.png
}
vm: "Виртуальные машины" {
  shape: image
  icon: vm-icon.webp
}
docker: "Docker" {
  shape: image
  icon: docker-logo.png
}
compose: "Docker Compose" {
  shape: image
  icon: docker-compose-icon.webp
}
swarm: "Docker Swarm" {
  shape: image
  icon: docker-swarm-icon.png
}
k8s: "Kubernetes" {
  shape: image
  icon: kubernetes-icon.webp
}

lambda: "Функции в облаке" {
  shape: image
  icon: aws-lambda.png
}

local -> vm
local -> docker
local -> lambda

docker -> compose
docker -> swarm
docker -> k8s
